name: Testando a regra de protection rule

on:
  branch_protection_rule:
    types: [created, edited, deleted]

jobs:
  print-modification:
    runs-on: ubuntu-latest
    steps:

      - name: Avisa sobre a modificação
        run: echo "Este workflow foi triggado pois uma regra de Branch Protection Rule foi alterada"



