name: Testando a regra de create branch

on:
  create

jobs:
  print-branch-or-tag-creation:
    runs-on: ubuntu-latest
    steps:

      - name: Avisa sobre a criação da branch ou tag
        run: echo "Uma nova branch ou tag foi criada no repositorio."



