name: Workflow Manual
on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar workflow de Build e Testes
        uses: ./.github/workflows/2-build-e-testes.yml  # workflow reutilizável

  