name: Meu Primeiro Desafio

on:
  workflow_dispatch:
    inputs:
      imagemdocker:
        description: Escolha uma imagem do docker para pull
        required: true
        type: string

jobs:
  dockerpull:
    runs-on: ubuntu-latest
    steps:
      - name: Input image:tag
        run: docker pull ${{github.event.inputs.imagemdocker}}

      - name: exibir imagem do docker 
        run: docker image ls
      
      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
            name: Analise de vulnerabilidade
            dockerhub-user: "paulofernandesdocker"
            dockerhub-password: "Bamaq#2027#"
            command: cves
            image: ${{github.event.inputs.imagemdocker}}
            to-latest: true
    



  
