name: Primeiro Workflow Linuxtips

on:
  push:
    branches:
      - main

jobs:
  giropops:
    runs-on: ubuntu-latest
    steps:
      - name: Confere versao do ubuntu
        run: cat /etc/os-release

      - name: Exibibir uma mensagem
        run: echo "Estou fazendo o curso de Github Actions da Linuxtips"


  