name: Build e Testes
on:
  workflow_call:       # workflow reutilizável

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build
        run: echo "Build realizado com sucesso!"

      - name: Testes
        run: |
          echo "Executando testes..."
          node test/index.test.js   # exit 0 = sucesso, exit 1 = falha
