name: Publicação Condicional
on:
  workflow_run:
    workflows: [Build e Testes]   # nome do workflow que dispara este
    types:
      - completed

jobs:
  fala-o-nome-do-curso:
    runs-on: ubuntu-latest
    steps:
      - name: Informa o nome do curso
        run: echo "O nome do seu curso é Teste"
